server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jahv/SpringCloudConfigTest-ConfigFiles #URL of the github repo
          search-paths: #Let look for paths inside repo
            - app*
          force-pull: true # Always go to the repo to read the values, otherwise read from local downloaded version

          repos:
            jndi:
              pattern:
                - "*/jndi"
              uri: https://github.com/jahv/SpringCloudConfigTest-ConfigFiles-jndi
              search-paths:
                - app*

          #username: Not needed since is a public repo
          #password:
